# Generated by Django 4.2.28 on 2026-02-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur')], default='agent', max_length=10),
        ),
    ]
