# Generated by Django 6.0 on 2026-01-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_identite', models.CharField(blank=True, choices=[('cni', "Carte Nationale d'Identité"), ('passeport', 'Passeport'), ('permis', 'Permis de conduire'), ('autre', 'Autre')], max_length=50)),
                ('numero_identite', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visiteur',
                'ordering': ['nom', 'prenoms'],
            },
        ),
    ]
