# Generated by Django 6.0 on 2026-01-02 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('visiteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_visite', models.CharField(choices=[('professionnelle', 'Professionnelle'), ('personnelle', 'Personnelle')], default='professionnelle', max_length=50)),
                ('date_visite', models.DateField(default=django.utils.timezone.now)),
                ('heure_entree', models.TimeField()),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('agent_entree', models.CharField(blank=True, max_length=100)),
                ('agent_sortie', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('correspondant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.correspondant')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.motifvisite')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='visiteurs.visiteur')),
            ],
            options={
                'verbose_name': 'Visite',
                'ordering': ['-date_visite', '-heure_entree'],
            },
        ),
    ]
