# Generated by Django 4.2.28 on 2026-02-24 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visiteurs', '0001_initial'),
        ('core', '0002_alter_utilisateur_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendez_vous', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('notes_confidentielles', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('correspondant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.correspondant')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_crees', to=settings.AUTH_USER_MODEL)),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.motifvisite')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='visiteurs.visiteur')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_rendez_vous', 'heure_debut'],
            },
        ),
    ]
