# Generated by Django 4.2.28 on 2026-02-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_utilisateur_role'),
        ('visites', '0002_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux_disponibilite', to='core.motifvisite')),
            ],
            options={
                'verbose_name': 'Créneau de disponibilité',
                'verbose_name_plural': 'Créneaux de disponibilité',
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='visites.creneaudisponibilite'),
        ),
    ]
