# Generated by Django 4.2.28 on 2026-02-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0003_creneaudisponibilite_rendezvous_creneau'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rendezvous',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'annule'), _negated=True), fields=('creneau',), name='unique_rdv_actif_par_creneau'),
        ),
    ]
