# Generated by Django 4.2.28 on 2026-02-24 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visites', '0004_rendezvous_unique_rdv_actif_par_creneau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
